bindkey "^[[3~" delete-char
if [ -x /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

mainconfig() {
  nixswitch "github:sven-m/system-config"
}

localconfig() {
  nixswitch ~/src/system-config
}