bindkey "^[[3~" delete-char
if [ -x /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

ghconfig() {
  nixswitch "github:sven-m/system-config?ref=${1:-main}"
}

localconfig() {
  nixswitch ~/src/system-config
}