#!/usr/bin/env bash

short_date="$(basename ${1%.md})"
dow=$(date -d "$short_date" +%u)  # 1=Mon .. 7=Sun
monday=$(date -d "$short_date - $((dow - 1)) days" +%Y-%m-%d)
week=$(date -d "$monday" +%V)
year=$(date -d "$monday" +%Y)

echo "# Week $week ($year)"
echo ""

for i in 0 1 2 3 4 5 6; do
  echo "## $(date -d "$monday + $i days" +"%a %-d %b")"
done
