
[font]
size = 14.0

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
]

[selection]
save_to_clipboard = true

[window]
dimensions = { columns = 120, lines = 40 }
