[font]
size = 20.0

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[selection]
save_to_clipboard = true

[window]
dimensions = { columns = 120, lines = 40 }
