-- Modelines off for prose.
--
-- Any line with whitespace before "vim:" is a modeline -- :h modeline defines
-- the leading part as "empty or any text followed by at least one blank
-- character", so a wiki line like
--
--   - [ ] practical vim: search
--
-- becomes `:set search` and errors with E518. Worse when it happens to parse:
-- "vim: set list" would silently take effect.
--
-- This has to be a markdown ftplugin rather than a vimwiki one. Filetype
-- detection runs as a BufReadPost autocommand, which is "before processing
-- modelines", and at that point a wiki file is still plain markdown; vimwiki
-- retypes it at BufWinEnter, which is after the modeline pass. So the vimwiki
-- ftplugin would be too late.
--
-- Deliberately not added to b:undo_ftplugin. Modelines are only read when the
-- file is read, so restoring the option on the markdown -> vimwiki retype would
-- change nothing, and off is the safer resting state.
vim.bo.modeline = false
