set-option -g detach-on-destroy off

# Reload config in the current session
bind r command-prompt -I 'source-file ~/.config/tmux/tmux.conf'
bind S display-popup -E -w 90% -h 90% "tmux-fzf-session-menu"
bind A command-prompt -I 'new-window -n "Apply nix config" conf wait apply'

bind e split-window -h -c "#{pane_current_path}" "$EDITOR ."
bind E split-window -c "#{pane_current_path}" "$EDITOR ." \; resize-pane -Z

bind W run-shell "tmux select-window -t notes 2>/dev/null || tmux new-window -c '$HOME/Documents/vimwiki' -n notes 'nvim -c VimwikiIndex'"

bind g new-window -c "#{pane_current_path}" lazygit

bind x run-shell "cd #{pane_current_path} && xed ."

bind % split-window -h -c '#{pane_current_path}'  # Split panes horizontal
bind -n M-\\ split-window -h -c '#{pane_current_path}'  # Split panes horizontal

bind \" split-window -c '#{pane_current_path}'  # Split panes vertically
bind -n M-Enter split-window -c '#{pane_current_path}'  # Split panes vertically

bind s choose-session -F "#{session_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5

bind -n C-M-h select-pane -L
bind -n C-M-j select-pane -D
bind -n C-M-k select-pane -U
bind -n C-M-l select-pane -R

set -g mouse on
set -g mode-keys vi

set-window-option -g automatic-rename on
set-option -g set-titles on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g status-position top

set -g cursor-style bar
set-option -g default-terminal 'tmux-256color'

set -g status-interval 1

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g @catppuccin_date_time_text " %a %b %d %H:%M:%S"

%hidden MODULE_NAME="branch"

set -g "@catppuccin_${MODULE_NAME}_icon" "\ue729 "
set -gF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_red}"
set -g "@catppuccin_${MODULE_NAME}_text" " #(git describe-worktree #{pane_current_path})"

source "$HOME/.config/tmux/plugins/catppuccin/utils/status_module.conf"

run "$HOME/.config/tmux/plugins/catppuccin/catppuccin.tmux"

set -g status-style "bg=default"
set -g status-right-length 150
set -g status-left-length 100

set -g status-left ""

set -g status-right ""
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_branch}"
set -ag status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_application}"
#set -ag status-right "#{E:@catppuccin_status_user}"
#set -agF status-right "#{E:@catppuccin_status_host}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
#set -ag status-right "#{E:@catppuccin_status_uptime}"
#set -agF status-right "#{E:@catppuccin_status_battery}"
#set -ag status-right "#{E:@catppuccin_status_date_time}"


run "$HOME/.config/tmux/plugins/cpu/cpu.tmux"
run "$HOME/.config/tmux/plugins/battery/battery.tmux"

run "$HOME/.config/tmux/plugins/resurrect/resurrect.tmux"
